CREATE TABLE [dbo].[User]
(
	[UUID] NVARCHAR(24) NOT NULL , 
    [UserName] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL, 
    [Age] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_User] PRIMARY KEY ([UUID]) 
)
